version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  adm:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
# - ./pgadmin:/var/lib/pgadmin/storage 
    ports:
      - "80:80"
      - "443:443"
    environment:
       PGADMIN_DEFAULT_EMAIL: pgadmin
       PGADMIN_DEFAULT_PASSWORD: pgadmin
