version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      LANG: ja_JP.UTF-8
  adm:
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - ./pgadmin:/var/lib/pgadmin:z 
#      - ./pgadmin:/var/lib/pgadmin/storage:z
    ports:
      - "80:80"
      - "443:443"
    environment:
       PGADMIN_DEFAULT_EMAIL: pgadmin
       PGADMIN_DEFAULT_PASSWORD: pgadmin
